### ISSUE TITLE
How to create sorting in tables?

### ISSUE THREAD

**Issue by plotters** [Skycoder42/QtDataSync#2]
Using QSortFilterProxyModel does not work in my case when trying to implement table sort. 

```auto proxyModel = new QSortFilterProxyModel(this);
        proxyModel->setSourceModel(_model);
        proxyModel->setFilterKeyColumn(1);
        ui->treeView->setModel(proxyModel);
        ui->treeView->setSortingEnabled(true);
        ui->treeView->sortByColumn(1);
```

It results in this error:
```qt.core.qabstractitemmodel.checkindex: Index QModelIndex(0,1,0x5650e42acf40,QSortFilterProxyModel(0x5650e42ac8a0)) is for model QSortFilterProxyModel(0x5650e42ac8a0) which is different from this model QtDataSync::DataStoreModel(0x5650e43f3870)```

Is there a way to implement this? I will adapt the example code to add this, but don't know how to start.

**Comment by Skycoder42** [comment]
I assume your `_model` is a `QtDataSync::DataStoreModel`? In that case, using a `QSortFilterProxyModel` should work.

The error you get comes from the [QAbstractItemModel::checkIndex](https://doc.qt.io/qt-5/qabstractitemmodel.html#checkIndex) method which is used internally to detect wrong usage of the model. The concrete error here indicates that you passed the `QModelIndex` of the `proxyModel` to a method of the `_model`, resulting in this error.

**Comment by plotters** [comment]
Thanks for the feedback. Indeed it works. One extra line of code solves the issue:

`auto pIndex = _proxyModel->mapToSource(index);`
`auto data = _model->loadObject(pIndex).value<DataModel>();`

Shall I make a pull request for the example?

**Comment by Skycoder42** [comment]
Glad I could help. But I don't think a pull request is neccessary for this, as this is standard behaviour for all models in Qt, i.e. there is no difference when using a proxy model between the datasync model and any other Qt model - except that I use this new method to prevent developers that use the model from missusing it - which is exactly what happend here - instead of potential random crashes you got a easy to identify error message.

But you can create a pull request if you want to. I will propably accept it, but again, no need for this extra work unless you want it to be in here.

**Comment by plotters** [comment]
Clear, thanks for the explanation and indeed a very useful error message.
